//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonScheduler.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classes_L
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Classes_L()
        {
            this.Group_L = new HashSet<Group_L>();
            this.Week_L = new HashSet<Week_L>();
        }
    
        public long ID { get; set; }
        public System.DateTime START_DATE { get; set; }
        public System.DateTime END_DATE { get; set; }
        public long CLASSES_TYPE_DV_ID { get; set; }
        public string SUBJECT_NAME { get; set; }
        public string SUBJECT_SHORT { get; set; }
        public long ROOM_ID { get; set; }
        public System.DateTime DATE_CREATED { get; set; }
        public Nullable<System.DateTime> DATE_MODIFIED { get; set; }
        public long ID_CREATED { get; set; }
        public long TEACHER_ID { get; set; }
        public Nullable<long> SPECIAL_LOCATION_ID { get; set; }
    
        public virtual Teacher_L Teacher_L { get; set; }
        public virtual SpecialLocation_L SpecialLocation_L { get; set; }
        public virtual Room_L Room_L { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group_L> Group_L { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Week_L> Week_L { get; set; }
    }
}
