//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonScheduler.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentTeacher_L
    {
        public long DEPARTMENT_ID { get; set; }
        public long TEACHER_ID { get; set; }
        public long POSITION_DV_ID { get; set; }
    
        public virtual Teacher_L Teacher_L { get; set; }
    }
}
