//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonScheduler.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DictionaryValue_L
    {
        public long DV_ID { get; set; }
        public string VALUE { get; set; }
        public long VALUE_TYPE { get; set; }
        public System.DateTime DATE_CREATED { get; set; }
        public Nullable<System.DateTime> DATE_MODIFIED { get; set; }
        public long ID_CREATED { get; set; }
        public long DICTIONARY_ID { get; set; }
    
        public virtual Dictionary_L Dictionary_L { get; set; }
    }
}
