//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonScheduler.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalUser_L
    {
        public long ID { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string LOGIN { get; set; }
        public string PASSWORD { get; set; }
        public string SERVER_ADDRESS { get; set; }
        public string SERVER_LOGIN { get; set; }
        public string SERVER_PASSWORD { get; set; }
        public System.DateTime DATE_CREATED { get; set; }
        public Nullable<System.DateTime> DATE_MODIFIED { get; set; }
        public long ROLE_ID { get; set; }
    
        public virtual Role_L Role_L { get; set; }
    }
}
